language: go
go:
  - 1.11.x
env:
  - GO111MODULE=on
script:
  - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o goapp src/main.go
  - docker build -f Dockerfile -t $DOCKER_USERNAME/goapp:$TRAVIS_BUILD_NUMBER .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/goapp:$TRAVIS_BUILD_NUMBER
