language: go
go:
  - 1.11.x
script:
  - cd /src && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o goapp main.go
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
